# Generated by Django 4.1.6 on 2023-02-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name_plural': 'Profesores'},
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombres',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='entregable',
            old_name='fecha_de_entrega',
            new_name='fechaDeEntrega',
        ),
    ]
